### ISSUE TITLE
Add runtime.txt to fix Cedar upgrade issue

### ISSUE THREAD

**Issue by mmmavis** [mozilla/hive-django#4]
Pushing to Heroku fails since Cedar 10 on Heroku is now deprecated and upgrading to Cedar 14 is mandatory.

The following shows the error log of my recent deploy attempt

``` bash
-----> Python app detected

ERROR:root:code for hash md5 was not found.

Traceback (most recent call last):

  File "/app/.heroku/python/lib/python2.7/hashlib.py", line 139, in <module>

    globals()[__func_name] = __get_hash(__func_name)

  File "/app/.heroku/python/lib/python2.7/hashlib.py", line 91, in __get_builtin_constructor

    raise ValueError('unsupported hash type ' + name)

ValueError: unsupported hash type md5

ERROR:root:code for hash sha1 was not found.

Traceback (most recent call last):

  File "/app/.heroku/python/lib/python2.7/hashlib.py", line 139, in <module>

    globals()[__func_name] = __get_hash(__func_name)

  File "/app/.heroku/python/lib/python2.7/hashlib.py", line 91, in __get_builtin_constructor

    raise ValueError('unsupported hash type ' + name)

ValueError: unsupported hash type sha1

ERROR:root:code for hash sha224 was not found.

Traceback (most recent call last):

  File "/app/.heroku/python/lib/python2.7/hashlib.py", line 139, in <module>

    globals()[__func_name] = __get_hash(__func_name)

  File "/app/.heroku/python/lib/python2.7/hashlib.py", line 91, in __get_builtin_constructor

    raise ValueError('unsupported hash type ' + name)

ValueError: unsupported hash type sha224

ERROR:root:code for hash sha256 was not found.

Traceback (most recent call last):

  File "/app/.heroku/python/lib/python2.7/hashlib.py", line 139, in <module>

    globals()[__func_name] = __get_hash(__func_name)

  File "/app/.heroku/python/lib/python2.7/hashlib.py", line 91, in __get_builtin_constructor

    raise ValueError('unsupported hash type ' + name)

ValueError: unsupported hash type sha256

ERROR:root:code for hash sha384 was not found.

Traceback (most recent call last):

  File "/app/.heroku/python/lib/python2.7/hashlib.py", line 139, in <module>

    globals()[__func_name] = __get_hash(__func_name)

  File "/app/.heroku/python/lib/python2.7/hashlib.py", line 91, in __get_builtin_constructor

    raise ValueError('unsupported hash type ' + name)

ValueError: unsupported hash type sha384

ERROR:root:code for hash sha512 was not found.

Traceback (most recent call last):

  File "/app/.heroku/python/lib/python2.7/hashlib.py", line 139, in <module>

    globals()[__func_name] = __get_hash(__func_name)

  File "/app/.heroku/python/lib/python2.7/hashlib.py", line 91, in __get_builtin_constructor

    raise ValueError('unsupported hash type ' + name)

ValueError: unsupported hash type sha512

Traceback (most recent call last):

  File "/app/.heroku/python/bin/pip", line 9, in <module>

    load_entry_point('pip==7.0.3', 'console_scripts', 'pip')()

  File "build/bdist.linux-x86_64/egg/pkg_resources/__init__.py", line 558, in load_entry_point

  File "build/bdist.linux-x86_64/egg/pkg_resources/__init__.py", line 2682, in load_entry_point

  File "build/bdist.linux-x86_64/egg/pkg_resources/__init__.py", line 2355, in load

  File "build/bdist.linux-x86_64/egg/pkg_resources/__init__.py", line 2361, in resolve

  File "/app/.heroku/python/lib/python2.7/site-packages/pip-7.0.3-py2.7.egg/pip/__init__.py", line 15, in <module>

    from pip.vcs import git, mercurial, subversion, bazaar  # noqa

  File "/app/.heroku/python/lib/python2.7/site-packages/pip-7.0.3-py2.7.egg/pip/vcs/mercurial.py", line 10, in <module>

    from pip.download import path_to_url

  File "/app/.heroku/python/lib/python2.7/site-packages/pip-7.0.3-py2.7.egg/pip/download.py", line 38, in <module>

    from pip._vendor import requests, six

  File "/app/.heroku/python/lib/python2.7/site-packages/pip-7.0.3-py2.7.egg/pip/_vendor/__init__.py", line 92, in load_module

    raise ImportError("No module named '%s'" % (name,))

ImportError: No module named 'pip._vendor.requests'

ERROR:root:code for hash md5 was not found.

Traceback (most recent call last):

  File "/app/.heroku/python/lib/python2.7/hashlib.py", line 139, in <module>

    globals()[__func_name] = __get_hash(__func_name)

  File "/app/.heroku/python/lib/python2.7/hashlib.py", line 91, in __get_builtin_constructor

    raise ValueError('unsupported hash type ' + name)

ValueError: unsupported hash type md5

ERROR:root:code for hash sha1 was not found.

Traceback (most recent call last):

  File "/app/.heroku/python/lib/python2.7/hashlib.py", line 139, in <module>

    globals()[__func_name] = __get_hash(__func_name)

  File "/app/.heroku/python/lib/python2.7/hashlib.py", line 91, in __get_builtin_constructor

    raise ValueError('unsupported hash type ' + name)

ValueError: unsupported hash type sha1

ERROR:root:code for hash sha224 was not found.

Traceback (most recent call last):

  File "/app/.heroku/python/lib/python2.7/hashlib.py", line 139, in <module>

    globals()[__func_name] = __get_hash(__func_name)

  File "/app/.heroku/python/lib/python2.7/hashlib.py", line 91, in __get_builtin_constructor

    raise ValueError('unsupported hash type ' + name)

ValueError: unsupported hash type sha224

ERROR:root:code for hash sha256 was not found.

Traceback (most recent call last):

  File "/app/.heroku/python/lib/python2.7/hashlib.py", line 139, in <module>

    globals()[__func_name] = __get_hash(__func_name)

  File "/app/.heroku/python/lib/python2.7/hashlib.py", line 91, in __get_builtin_constructor

    raise ValueError('unsupported hash type ' + name)

ValueError: unsupported hash type sha256

ERROR:root:code for hash sha384 was not found.

Traceback (most recent call last):

  File "/app/.heroku/python/lib/python2.7/hashlib.py", line 139, in <module>

    globals()[__func_name] = __get_hash(__func_name)

  File "/app/.heroku/python/lib/python2.7/hashlib.py", line 91, in __get_builtin_constructor

    raise ValueError('unsupported hash type ' + name)

ValueError: unsupported hash type sha384

ERROR:root:code for hash sha512 was not found.

Traceback (most recent call last):

  File "/app/.heroku/python/lib/python2.7/hashlib.py", line 139, in <module>

    globals()[__func_name] = __get_hash(__func_name)

  File "/app/.heroku/python/lib/python2.7/hashlib.py", line 91, in __get_builtin_constructor

    raise ValueError('unsupported hash type ' + name)

ValueError: unsupported hash type sha512

Traceback (most recent call last):

  File "/app/tmp/buildpacks/python/vendor/pip-pop/pip-diff", line 15, in <module>

    from pip.req import parse_requirements

  File "/app/tmp/buildpacks/python/vendor/pip-pop/pip/__init__.py", line 15, in <module>

    from pip.vcs import git, mercurial, subversion, bazaar  # noqa

  File "/app/tmp/buildpacks/python/vendor/pip-pop/pip/vcs/mercurial.py", line 10, in <module>

    from pip.download import path_to_url

  File "/app/tmp/buildpacks/python/vendor/pip-pop/pip/download.py", line 38, in <module>

    from pip._vendor import requests, six

  File "/app/tmp/buildpacks/python/vendor/pip-pop/pip/_vendor/requests/__init__.py", line 58, in <module>

    from . import utils

  File "/app/tmp/buildpacks/python/vendor/pip-pop/pip/_vendor/requests/utils.py", line 26, in <module>

    from .compat import parse_http_list as _parse_list_header

  File "/app/tmp/buildpacks/python/vendor/pip-pop/pip/_vendor/requests/compat.py", line 7, in <module>

    from .packages import chardet

  File "/app/tmp/buildpacks/python/vendor/pip-pop/pip/_vendor/requests/packages/__init__.py", line 3, in <module>

    from . import urllib3

  File "/app/tmp/buildpacks/python/vendor/pip-pop/pip/_vendor/requests/packages/urllib3/__init__.py", line 10, in <module>

    from .connectionpool import (

  File "/app/tmp/buildpacks/python/vendor/pip-pop/pip/_vendor/requests/packages/urllib3/connectionpool.py", line 31, in <module>

    from .connection import (

  File "/app/tmp/buildpacks/python/vendor/pip-pop/pip/_vendor/requests/packages/urllib3/connection.py", line 45, in <module>

    from .util.ssl_ import (

  File "/app/tmp/buildpacks/python/vendor/pip-pop/pip/_vendor/requests/packages/urllib3/util/__init__.py", line 5, in <module>

    from .ssl_ import (

  File "/app/tmp/buildpacks/python/vendor/pip-pop/pip/_vendor/requests/packages/urllib3/util/ssl_.py", line 2, in <module>

    from hashlib import md5, sha1, sha256

ImportError: cannot import name md5

     $ pip install -r requirements.txt

       ERROR:root:code for hash md5 was not found.

       Traceback (most recent call last):

         File "/app/.heroku/python/lib/python2.7/hashlib.py", line 139, in <module>

           globals()[__func_name] = __get_hash(__func_name)

         File "/app/.heroku/python/lib/python2.7/hashlib.py", line 91, in __get_builtin_constructor

           raise ValueError('unsupported hash type ' + name)

       ValueError: unsupported hash type md5

       ERROR:root:code for hash sha1 was not found.

       Traceback (most recent call last):

         File "/app/.heroku/python/lib/python2.7/hashlib.py", line 139, in <module>

           globals()[__func_name] = __get_hash(__func_name)

         File "/app/.heroku/python/lib/python2.7/hashlib.py", line 91, in __get_builtin_constructor

           raise ValueError('unsupported hash type ' + name)

       ValueError: unsupported hash type sha1

       ERROR:root:code for hash sha224 was not found.

       Traceback (most recent call last):

         File "/app/.heroku/python/lib/python2.7/hashlib.py", line 139, in <module>

           globals()[__func_name] = __get_hash(__func_name)

         File "/app/.heroku/python/lib/python2.7/hashlib.py", line 91, in __get_builtin_constructor

           raise ValueError('unsupported hash type ' + name)

       ValueError: unsupported hash type sha224

       ERROR:root:code for hash sha256 was not found.

       Traceback (most recent call last):

         File "/app/.heroku/python/lib/python2.7/hashlib.py", line 139, in <module>

           globals()[__func_name] = __get_hash(__func_name)

         File "/app/.heroku/python/lib/python2.7/hashlib.py", line 91, in __get_builtin_constructor

           raise ValueError('unsupported hash type ' + name)

       ValueError: unsupported hash type sha256

       ERROR:root:code for hash sha384 was not found.

       Traceback (most recent call last):

         File "/app/.heroku/python/lib/python2.7/hashlib.py", line 139, in <module>

           globals()[__func_name] = __get_hash(__func_name)

         File "/app/.heroku/python/lib/python2.7/hashlib.py", line 91, in __get_builtin_constructor

           raise ValueError('unsupported hash type ' + name)

       ValueError: unsupported hash type sha384

       ERROR:root:code for hash sha512 was not found.

       Traceback (most recent call last):

         File "/app/.heroku/python/lib/python2.7/hashlib.py", line 139, in <module>

           globals()[__func_name] = __get_hash(__func_name)

         File "/app/.heroku/python/lib/python2.7/hashlib.py", line 91, in __get_builtin_constructor

           raise ValueError('unsupported hash type ' + name)

       ValueError: unsupported hash type sha512

       Traceback (most recent call last):

         File "/app/.heroku/python/bin/pip", line 9, in <module>

           load_entry_point('pip==8.1.1', 'console_scripts', 'pip')()

         File "build/bdist.linux-x86_64/egg/pkg_resources/__init__.py", line 549, in load_entry_point

         File "build/bdist.linux-x86_64/egg/pkg_resources/__init__.py", line 2543, in load_entry_point

         File "build/bdist.linux-x86_64/egg/pkg_resources/__init__.py", line 2203, in load

         File "build/bdist.linux-x86_64/egg/pkg_resources/__init__.py", line 2209, in resolve

         File "/app/.heroku/python/lib/python2.7/site-packages/pip-8.1.1-py2.7.egg/pip/__init__.py", line 16, in <module>

           from pip.vcs import git, mercurial, subversion, bazaar  # noqa

         File "/app/.heroku/python/lib/python2.7/site-packages/pip-8.1.1-py2.7.egg/pip/vcs/mercurial.py", line 9, in <module>

           from pip.download import path_to_url

         File "/app/.heroku/python/lib/python2.7/site-packages/pip-8.1.1-py2.7.egg/pip/download.py", line 39, in <module>

           from pip._vendor import requests, six

         File "/app/.heroku/python/lib/python2.7/site-packages/pip-8.1.1-py2.7.egg/pip/_vendor/requests/__init__.py", line 58, in <module>

           from . import utils

         File "/app/.heroku/python/lib/python2.7/site-packages/pip-8.1.1-py2.7.egg/pip/_vendor/requests/utils.py", line 26, in <module>

           from .compat import parse_http_list as _parse_list_header

         File "/app/.heroku/python/lib/python2.7/site-packages/pip-8.1.1-py2.7.egg/pip/_vendor/requests/compat.py", line 7, in <module>

           from .packages import chardet

         File "/app/.heroku/python/lib/python2.7/site-packages/pip-8.1.1-py2.7.egg/pip/_vendor/requests/packages/__init__.py", line 29, in <module>

           import urllib3

       ImportError: No module named urllib3

 !     Push rejected, failed to compile Python app
```

Solution: add a `runtime.txt` to pin Python version as mentioned in https://github.com/toolness/htmlpad/pull/2#issuecomment-207770808 :wink:

**Comment by mmmavis** [comment]
fixed in https://github.com/mozilla/hive-django/pull/3
